import type { EquipmentPhysicsDelta } from '../types/catalog'
import generated from './equipmentPhysics.generated.json'

/**
 * Precomputed equipment physics deltas, generated by
 * `scripts/equipment-physics/compute-equipment-physics.mjs` from the same
 * speed-data tables and solver the classifiers used to run at runtime.
 *
 * Why precomputed: `solveEquipmentDelta` (see `physics/equipment.ts`) is a
 * nested bisection - ~60x60x60 force evaluations per solve - and classifying
 * the full catalog runs it for every measured frame x level and every
 * measured wheel. That was 4-11.5s of CPU on Workers production hardware,
 * paid inside the first request of every fresh isolate. The solver's inputs
 * are all static repo data, so the solve belongs at build time; runtime
 * reads this table instead.
 *
 * The table is complete by construction - every `FRAME_SPEED_DATA` /
 * `TT_FRAME_SPEED_DATA` name at every level 0-5, every `WHEEL_SPEED_DATA`
 * name - and `npm run validate` re-solves everything and fails the build on
 * any drift (`validate:equipment-physics`), the same discipline as
 * `validate:speed-data`. A missing entry here therefore means the speed data
 * changed without regeneration, and the lookups below throw rather than
 * silently degrade - deliberately no runtime-solver fallback.
 *
 * Levels are whole stages 0-5, which is the entire real domain: Zwift's
 * upgrade stages are integers, the API schemas snap incoming levels to
 * integers (`apiQuerySchemas.ts`), and `classifyFrame` rounds defensively.
 */
interface GeneratedEquipmentPhysics {
  /** Standard frames: delta per upgrade level, indexed 0-5. */
  frames: Record<string, EquipmentPhysicsDelta[]>
  /** TT frames, solved against the TT baseline - see `solveFrameEquipmentDelta`. */
  ttFrames: Record<string, EquipmentPhysicsDelta[]>
  wheels: Record<string, EquipmentPhysicsDelta>
  /** See the comment on this constant in `physics/equipment.ts`. */
  ttDiscResidualCdaDeltaM2: number
}

const TABLE = generated as unknown as GeneratedEquipmentPhysics

const REGENERATE = 'run `npm run equipment-physics:compute` and commit the regenerated shared/data/equipmentPhysics.generated.json'

export function precomputedFrameDelta(name: string, level: number, isTT: boolean): EquipmentPhysicsDelta {
  const delta = (isTT ? TABLE.ttFrames : TABLE.frames)[name]?.[level]
  if (!delta) throw new Error(`No precomputed equipment physics for ${isTT ? 'TT ' : ''}frame "${name}" at level ${level} - ${REGENERATE}`)
  return delta
}

export function precomputedWheelDelta(name: string): EquipmentPhysicsDelta {
  const delta = TABLE.wheels[name]
  if (!delta) throw new Error(`No precomputed equipment physics for wheel "${name}" - ${REGENERATE}`)
  return delta
}

export const PRECOMPUTED_TT_DISC_RESIDUAL_CDA_DELTA_M2 = TABLE.ttDiscResidualCdaDeltaM2
