import type { RouteElevationPoint, SurfaceComposition, SurfaceSegment } from '../types/catalog'
import generated from './routeSurfaces.generated.json'

/**
 * Real per-route surface data, generated by
 * `scripts/route-surfaces/compute-route-surfaces.mjs` from each route's
 * actual GPS trace (via Strava) intersected against zwiftmap's world surface
 * polygons - see that script and `shared/utils/surfaceGeometry.ts` for the
 * methodology, and `scripts/route-surfaces/README.md` for how to (re)run it.
 *
 * Starts empty until that script has been run at least once - routes not
 * covered here (either because generation hasn't run yet, or because the
 * route has no Strava segment, e.g. most event-only routes) fall back to the
 * hand-curated/heuristic estimate in `routeTerrain.ts`. `segments` and
 * `elevationProfile` are optional since they were added after `composition` -
 * entries generated before those changes won't have them until the script is
 * re-run.
 */
interface GeneratedRouteSurface {
  composition: SurfaceComposition
  segments?: SurfaceSegment[]
  /** Real per-lap elevation profile from the same GPS trace, simplified - see `shared/utils/elevationGeometry.ts`. */
  elevationProfile?: RouteElevationPoint[]
  generatedAt: string
  stravaSegmentId: number
}

const ROUTE_SURFACES = generated as unknown as Record<string, GeneratedRouteSurface>

export function getGeneratedRouteSurface(slug: string): GeneratedRouteSurface | undefined {
  return ROUTE_SURFACES[slug]
}
