import type { RouteElevationPoint, SurfaceComposition, SurfaceSegment } from '../types/catalog'
import generated from './routeSurfaces.generated.json'

/**
 * Real per-route surface data, generated by
 * `scripts/route-surfaces/compute-route-surfaces.mjs` from each route's
 * actual GPS trace (via Strava) intersected against zwiftmap's world surface
 * polygons - see that script and `shared/utils/surfaceGeometry.ts` for the
 * methodology, and `scripts/route-surfaces/README.md` for how to (re)run it.
 *
 * Starts empty until that script has been run at least once - routes not
 * covered here (either because generation hasn't run yet, or because the
 * route has no Strava segment, e.g. most event-only routes) fall back to the
 * hand-curated/heuristic estimate in `routeTerrain.ts`. `segments` and
 * `elevationProfile` are optional since they were added after `composition` -
 * entries generated before those changes won't have them until the script is
 * re-run.
 *
 * Keys are whatever `route.slug` zwift-data currently exposes, which for a
 * handful of event-only routes is a bare numeric id rather than a readable
 * name (`4092230492` is Urumaze, `2919739330` Mech Isle Mayhem, `362278484`
 * Twilight Crit, `811898717` WhatYumeziWereLost). Those keys have to be
 * re-pointed if zwift-data ever gives those routes readable slugs, together
 * with the matching `routeSlug` values in `shared/data/events/` - a stale key
 * matches nothing and drops the route back to the heuristic estimate without
 * failing anything. `compute-route-surfaces.mjs` warns about keys that match
 * no route, which is how that gets caught.
 */
interface GeneratedRouteSurface {
  composition: SurfaceComposition
  /** LAP-relative (normalized - see `scripts/route-surfaces/normalize.mjs` and issue #126). */
  segments?: SurfaceSegment[]
  /** Real per-lap elevation profile from the same GPS trace, simplified - see `shared/utils/elevationGeometry.ts`. Lap-relative, first point `{0,0}`. */
  elevationProfile?: RouteElevationPoint[]
  /**
   * Present only when the source trace covered the lead-in as well
   * (`traceCoveredLeadIn`): the lead-in's own measured surface stretches and
   * elevation shape, km/m relative to the RIDE start (which is the lead-in's
   * own start). Split off by the normalizer so the lap arrays above stay
   * purely lap-relative without throwing the lead-in's real data away.
   */
  leadInSegments?: SurfaceSegment[]
  leadInElevationProfile?: RouteElevationPoint[]
  traceCoveredLeadIn?: boolean
  generatedAt: string
  stravaSegmentId: number
}

const ROUTE_SURFACES = generated as unknown as Record<string, GeneratedRouteSurface>

export function getGeneratedRouteSurface(slug: string): GeneratedRouteSurface | undefined {
  return ROUTE_SURFACES[slug]
}
