import type { GeneratedSegmentPlacement, SegmentPlacementsFile } from '../utils/segmentHostPlacement'
import generated from './segmentPlacements.generated.json'

/**
 * Placements measured by matching a segment's recorded track to its host
 * route's, generated by `scripts/segment-placements/compute-segment-placements.mjs`
 * (`npm run segment-placements:compute`) from `zwift-data/streams` - see
 * `shared/utils/segmentHostPlacement.ts` for which hosts are placed and
 * `shared/utils/segmentMatching.ts` for the matching rules (#273). A
 * segment `zwift-data` has no track for is placed by the track fetched for
 * its hand-found Strava id (`segmentStravaIdSupplement.ts`), which the
 * generator reads from the committed `segmentStreams.supplement.json` -
 * never imported here, so it stays out of the app (#274).
 *
 * Each is in the shape and the frame of a `zwift-data` `segmentsOnRoute`
 * entry - km along the route's own recorded track from the lap start - so
 * `getRoutesWithMeta` merges them in as they are and `computeTerrain` puts
 * them in official km with the package's own (`placementsInOfficialKm`). Only pairs `zwift-data` has not placed itself are here. The
 * file's `unplaced` list (every host that could not be placed, and why) is
 * the generator's report and is not read at runtime.
 */
const FILE = generated as SegmentPlacementsFile

export function getGeneratedSegmentPlacements(routeSlug: string): GeneratedSegmentPlacement[] {
  return FILE.placements[routeSlug] ?? []
}
