import type { GeneratedSegmentPlacement, SegmentPlacementsFile } from '../utils/segmentHostPlacement'
import generated from './segmentPlacements.generated.json'

/**
 * Placements measured by matching a segment's recorded track to its host
 * route's, generated by `scripts/segment-placements/compute-segment-placements.mjs`
 * (`npm run segment-placements:compute`) from `zwift-data/streams` - see
 * `shared/utils/segmentHostPlacement.ts` for which hosts are placed and
 * `shared/utils/segmentMatching.ts` for the matching rules (#273).
 *
 * Each is in the shape and the frame of a `zwift-data` `segmentsOnRoute`
 * entry - km along the route's own recorded track from the lap start - so
 * `getRoutesWithMeta` merges them in as they are and `traceScale` applies to
 * them unchanged. Only pairs `zwift-data` has not placed itself are here. The
 * file's `unplaced` list (every host that could not be placed, and why) is
 * the generator's report and is not read at runtime.
 */
const FILE = generated as SegmentPlacementsFile

export function getGeneratedSegmentPlacements(routeSlug: string): GeneratedSegmentPlacement[] {
  return FILE.placements[routeSlug] ?? []
}
