name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

permissions: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Filter relevant paths
        id: filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          filters: |
            workflows:
              - ".github/workflows/**"

  zizmor:
    name: Run zizmor 🌈
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
      contents: read # Needed to clone the repo.
      actions: read # Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        if: needs.changes.outputs.workflows == 'true'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        if: needs.changes.outputs.workflows == 'true'
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
